[package]
name = "commander-core"
version = "1.1.3"
authors = ["dimos <doubledimos@outlook.com>"]
edition = "2018"
description = "This crate is used by commander-rust only."
license-file = "./LICENSE"

[dependencies]
lazy_static = "1.2.0"
