[package]
authors = ["dimos <doubledimos@outlook.com>"]
edition = "2018"
name = "hash"
version = "0.1.0"
description = "generating hash of files or string, using MD5 hash"

[dependencies]
md5 = "0.6.1"

[dependencies.commander-rust]
path = "../"
features = ["en"]
